{% set version = "0.2.0" %}
{% set sha256 = "18c4cb1ea88f743e59c3802733d9d151f3b0c1eebf3aca54a3b0b5429e56a70e" %}

package:
    name: ipympl
    version: {{ version }}

source:
    fn: ipympl-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/i/ipympl/ipympl-{{ version }}.tar.gz
    sha256: {{ sha256 }}

build:
    noarch: python
    number: 1
    script: python -m pip install --no-deps --ignore-installed .

requirements:
    build:
        - python
        - setuptools
        - jupyter
    run:
        - python
        - ipywidgets >=7.0.0,<8.0
        - ipykernel >=4.7
        - matplotlib >=2.0.0
        - six

test:
    imports:
        - ipympl

about:
    home: https://github.com/matplotlib/jupyter-matplotlib
    license: BSD 3-Clause
    license_family: BSD
    license_file: LICENSE
    summary: Matplotlib Jupyter Extension

extra:
  recipe-maintainers:
    - JasonGrout
    - SylvainCorlay
    - tacaswell
    - blink1073
