{% set version = "0.5.8" %}
{% set js_version = "0.7.3" %}
{% set sha256 = "0e2f2e540a2dfea61524b7993fc8552c9236b1aaa3826e1f382c75cb2fa5c382" %}

package:
  name: ipympl
  version: {{ version }}

source:
  fn: ipympl-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/i/ipympl/ipympl-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - setuptools
    - jupyter
    - pip
  run:
    - python
    - ipywidgets >=7.5.0,<8.0
    - ipykernel >=4.7
    - matplotlib-base >=2.2.0
    - six

test:
  imports:
    - ipympl
  commands:
    - test -f ${PREFIX}/share/jupyter/nbextensions/jupyter-matplotlib/extension.js                                     # [unix]
    - test -f ${PREFIX}/share/jupyter/nbextensions/jupyter-matplotlib/index.js                                         # [unix]
    - test -f ${PREFIX}/share/jupyter/lab/extensions/jupyter-matplotlib-{{ js_version }}.tgz                              # [unix]
    - if exist %PREFIX%\\share\\jupyter\\nbextensions\\jupyter-matplotlib\\extension.js (exit 0) else (exit 1)         # [win]
    - if exist %PREFIX%\\share\\jupyter\\nbextensions\\jupyter-matplotlib\\index.js (exit 0) else (exit 1)             # [win]
    - if exist %PREFIX%\\share\\jupyter\\lab\\extensions\\jupyter-matplotlib-{{ js_version }}.tgz (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/matplotlib/ipympl
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Matplotlib Jupyter Extension

extra:
  recipe-maintainers:
    - JasonGrout
    - SylvainCorlay
    - tacaswell
    - blink1073
    - martinRenou
