{% set version = "0.6.2" %}
{% set sha256 = "e285e399f9e0e1c3332a7c135c8ce14358f234e3309e9c0d937bf0cb131dd9cc" %}

package:
  name: ipympl
  version: {{ version }}

source:
  fn: ipympl-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/i/ipympl/ipympl-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python >=3.6
    - setuptools
    - nodejs
    - jupyterlab =3
    - jupyter-packaging
    - pip
  run:
    - python >=3.6
    - ipywidgets >=7.6.0,<8.0
    - ipykernel >=4.7
    - matplotlib-base >=2.2.0
    - six

test:
  imports:
    - ipympl
  commands:
    - test -f ${PREFIX}/share/jupyter/nbextensions/jupyter-matplotlib/extension.js                               # [unix]
    - test -f ${PREFIX}/share/jupyter/nbextensions/jupyter-matplotlib/index.js                                   # [unix]
    - test -f ${PREFIX}/share/jupyter/labextensions/jupyter-matplotlib/package.json                              # [unix]
    - if exist %PREFIX%\\share\\jupyter\\nbextensions\\jupyter-matplotlib\\extension.js (exit 0) else (exit 1)   # [win]
    - if exist %PREFIX%\\share\\jupyter\\nbextensions\\jupyter-matplotlib\\index.js (exit 0) else (exit 1)       # [win]
    - if exist %PREFIX%\\share\\jupyter\\labextensions\\jupyter-matplotlib\\package.json (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/matplotlib/ipympl
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Matplotlib Jupyter Extension

extra:
  recipe-maintainers:
    - JasonGrout
    - SylvainCorlay
    - tacaswell
    - blink1073
    - martinRenou
