{% set version = "0.9.5" %}
{% set sha256 = "b702db4bd1138cee21ab3c731e1c1bc5c3efbfa81b9b42a1820f79122d946dc8" %}

package:
  name: ipympl
  version: {{ version }}

source:
  fn: ipympl-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/i/ipympl/ipympl-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - hatchling
    - hatch-nodejs-version
    - hatch-jupyter-builder
    - yarn
    - jupyterlab =4
    - pip
  run:
    - python >={{ python_min }}
    - ipython <9
    - numpy
    - ipython_genutils
    - pillow
    - traitlets <6
    - ipywidgets >=7.6.0,<9
    - matplotlib-base >=2.2.0,<4

test:
  requires:
    - python {{ python_min }}
  imports:
    - ipympl
  commands:
    - test -f ${PREFIX}/share/jupyter/nbextensions/jupyter-matplotlib/extension.js                     # [unix]
    - test -f ${PREFIX}/share/jupyter/nbextensions/jupyter-matplotlib/index.js                         # [unix]
    - test -f ${PREFIX}/share/jupyter/labextensions/jupyter-matplotlib/package.json                    # [unix]
    - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\jupyter-matplotlib\\extension.js (exit 1)   # [win]
    - if not exist %PREFIX%\\share\\jupyter\\nbextensions\\jupyter-matplotlib\\index.js (exit 1)       # [win]
    - if not exist %PREFIX%\\share\\jupyter\\labextensions\\jupyter-matplotlib\\package.json (exit 1)  # [win]

about:
  home: https://github.com/matplotlib/ipympl
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Matplotlib Jupyter Extension

extra:
  recipe-maintainers:
    - JasonGrout
    - SylvainCorlay
    - tacaswell
    - blink1073
    - martinRenou
