{% set version = "0.5.2" %}
{% set sha256 = "25801eeaa2d4f24d4fba7721ba8b54526ee7052cf1c6817a414ff61d7dfd6285" %}

package:
  name: ipympl
  version: {{ version }}

source:
  fn: ipympl-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/i/ipympl/ipympl-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - setuptools
    - jupyter
    - pip
  run:
    - python
    - ipywidgets >=7.5.0,<8.0
    - ipykernel >=4.7
    - matplotlib-base >=2.2.0
    - six

test:
  imports:
    - ipympl

about:
  home: https://github.com/matplotlib/jupyter-matplotlib
  license: BSD 3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Matplotlib Jupyter Extension

extra:
  recipe-maintainers:
    - JasonGrout
    - SylvainCorlay
    - tacaswell
    - blink1073
    - martinRenou
