appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
travis:
  secure: {BINSTAR_TOKEN: NlcvVnZIapKiNWsHQOp2CYYoO0AowL5xmirXv9h9J7DcrCGOE7OK3mA6WPVD+ILGLMkaEzGx02tgsiyYlj84ovIBL0JQExau1mn1PMwZNCtPMxeyibQrnKkjRD3tEC3qb+KBrJLpKUHGo2GTY3gbQICpFJehNvySA8kjQ2G2d5FrgM2UcJQ2J+UckJl5K4KJgCjdGbvDIUtr4fIIwdB/Z2b+/wcnhcLQC0UFVH1x+jwtPuqSxAh85ahfUUJIOKsfVo1w7y1AxtE45MPTRArm38tgc5mykOvkZiOGeM1L9xg37ME7Be0kwfV9/IalNq/uUrIQPFzGI0JuJUyJRSGbFP2lTE3XyGliEzT4ch0BVA3PomHO6VUiD6CqtS4ceZrCv6xmIdOrFlZwa6jx33J3XL/AgcVTbjHsQSlVsGmEzgk5q+exvZsa8L8jDyE17anqfY/ZHCGqD0Q1xMbzbp1w+foewQobCnr4E6bHPtBzXjqykkNOhtL+cX47mChLLp4MnBJMKObTOi0qcLMKQjqaZ/e5xkEHCUEcuF6qd2FswFejYrNvML4soi4yy92tOEvSuOTIzwvPlMOd5WuzbxikI8OzIp9hqsoGDtSCGPIudQWFkdeqLHcryUwrJp+WkqOuoojKXnHYHtyLSHL13ajs5KQYswoLRM+L7MeldSdyHRU=}
provider:
  win: azure
conda_forge_output_validation: true
